import { ImageStyle, Platform, TextStyle, ViewStyle } from "react-native"
import { color, spacing, typography } from "../../theme"
import { fontSizes, screenHeight, screenWidth } from "../../theme/size"

export const generateBillScreen = {
  FULL: {
    flex: 1,
    backgroundColor: color.palette.darkPurple,
  } as ViewStyle,
  BTNGENERATEBILL: {
    alignSelf: "center",
    height: screenWidth * 0.1,
    width: screenWidth * 0.4,
    textAlign: "center",
    color: "black",
    borderColor: "white",
    borderWidth: 1,
    borderRadius: 5,
    justifyContent: "center",
  } as ViewStyle,
  TXTGENERATEBILL: {
    color: color.palette.white,
    textAlign: "center",
  } as TextStyle,
  SAVRCARD_BUTTON_STYLE: ({
    marginTop: screenWidth * 0.12,
    backgroundColor: color.palette.darkPurple,
    marginBottom: screenWidth * 0.1,
  } as unknown) as ViewStyle,
  TXT_SAVECARD: {
    letterSpacing: 2,
    fontFamily: typography.primary,
    fontSize: fontSizes.font15,
    fontStyle: "normal",
    marginTop: -5,
    fontWeight: "bold",
    color: color.palette.white,
  } as TextStyle,
  TXT_TITLE_STYLE: {
    fontSize: screenWidth * 0.05,
    color: color.palette.white,
    textAlign: "center",
    alignSelf: "flex-start",
    marginLeft: "23%",
    fontFamily: typography.primary
  } as TextStyle,
  TXT_INPUT_STYLE: {
    borderBottomWidth: 1,
    borderColor: color.palette.lighterGrey,
    backgroundColor: color.palette.paleGrey,
    width: screenWidth * 0.87,
    height: screenHeight * 0.05,
    color: color.palette.black,
    paddingLeft: 5,
    alignSelf: "center",
    fontSize: screenHeight * 0.022,
  } as TextStyle,
  DATE_OF_INVOICE_STYLE: {
    backgroundColor: color.palette.paleGreyTwo,
    width: screenWidth * 0.87,
    height: screenHeight * 0.065,
    borderBottomWidth: 1,
    borderColor: color.palette.lighterGrey,
    paddingLeft: 5,
    alignSelf: "center",
    justifyContent: "center",
  } as ViewStyle,
  TXT_DATE_INVOICE: {
    color: color.palette.black,
  } as TextStyle,
  TXT_INPUT_STYLE_WITH_PENCIL: {
    borderBottomWidth: 1,
    borderColor: color.palette.lighterGrey,
    backgroundColor: color.palette.paleGrey,
    width: screenWidth * 0.77,
    height: 44,
    color: color.palette.black,
    paddingLeft: 5,
    alignSelf: "center",
  } as TextStyle,
  CONTAINER_OVERRIDE_STYLE: {
    paddingVertical: 0,
  } as ViewStyle,
  PERSONALID_HINT_STYLE: {
    color: color.palette.blue,
    fontFamily: typography.primary,
    fontSize: fontSizes.font12,
    marginTop: 5,
    width: screenWidth * 0.8,
    alignSelf: "center",
  } as TextStyle,
  sectionViewStyle: {
    backgroundColor: color.palette.purpple,
    left: 5,
    padding: 5,
    position: "absolute",
    top: -15,
  } as TextStyle,
  containerOfTextFields: {
    borderColor: "white",
    borderWidth: 2,
    marginTop: 20,
    marginHorizontal: 10,
    marginBottom: 10,
    paddingBottom: 20,
  } as ViewStyle,
  BTNSGSTSTYLE: {
    flexDirection: "row",
    marginTop: 10,
    marginRight: 15,
    marginBottom: 5,
  } as ViewStyle,
  GSTTYPESTYLE: {
    fontSize: fontSizes.font14,
    fontFamily: typography.primary,
    color: color.palette.white,
    marginTop: 20,
    marginLeft: 15,
  } as TextStyle,
  SUBCONTAINEROFGSTTYPE: {
    flexDirection: "row",
    paddingHorizontal: 15,
    // marginTop: 10
  } as ViewStyle,
  RADIOBUTTONSTYLE: {
    height: 22,
    width: 22,
    borderWidth: 2,
    borderColor: color.palette.white,
    borderRadius: 11,
    justifyContent: "center",
    marginRight: 5,
  } as ViewStyle,
  SELECTEDCIRCLE_DOT_STYLE: {
    height: 10,
    width: 10,
    backgroundColor: color.palette.white,
    borderColor: color.palette.white,
    borderRadius: 5,
    borderWidth: 0.5,
    alignSelf: "center",
  } as ViewStyle,
  EDIT_ICON_STYLE: {
    height: screenWidth * 0.04,
    width: screenWidth * 0.04,
    alignSelf: "center",
    flex: 1,
  } as ImageStyle,
  BTNEDITTEXTFIELD: {
    justifyContent: "center",
    alignItems: "center",
    width: screenWidth * 0.1,
    height: 44,
    backgroundColor: color.palette.paleGreyTwo,
  } as ViewStyle,
  HORIZONTALVIEW: {
    flexDirection: "row",
    alignSelf: "center",
    overflow: 'hidden',
  } as ViewStyle,
  TXT_LABEL_STYLE: {
    marginLeft: 20,
    marginTop: 15,
    marginBottom: 5,

  } as TextStyle,
  FLATLIST_STYLE: {
    marginTop: screenWidth * 0.02,
    height: 150,
    width: screenWidth * 0.87,
    alignSelf: "center",
    backgroundColor: color.palette.paleGreyTwo,
  } as ViewStyle,
  CELL_CONTAINER: {
    margin: 3,
  } as ViewStyle,
  TXT_PARTY_NAME: {
    color: color.palette.black,
    fontSize: fontSizes.font15,
  } as TextStyle,
  CONTAINER_PARTYLIST: {
    width: screenWidth * 0.87,
    alignSelf: "center",
  } as ViewStyle,
  HORIZONTAL_VIEW_FOR_RADIOBUTTON: {
    flexDirection: "row",
    overflow: 'hidden',
  } as ViewStyle,
  HORIZONTAL_VIEW_FIELDS: {
    flexDirection: "row",
    width: screenWidth * 0.55,
  } as ViewStyle,
  SELECTEDCIRCLESTYLE: {
    height: 22,
    width: 22,
    borderWidth: 0.5,
    borderColor: color.palette.pink,
    borderRadius: 11,
  } as ViewStyle,
  UNSELECTEDROUNDCIRCLE_STYLE: {
    height: 22,
    width: 22,
    borderWidth: 0.5,
    borderColor: color.palette.lightGreyBlue,
    borderRadius: 11,
  } as ViewStyle,
  TXT_SUPPLY_SERVICE_NAME: {
    color: color.palette.white,
    fontFamily: typography.primary,
    marginRight: 10,
    marginLeft: screenWidth * 0.02,
  } as TextStyle,
  CONTAINEROF_SERVICE: {
    flexDirection: "row",
    flex: 1,
    marginTop: 10,
    marginHorizontal: 22,
    marginBottom: 10,
  } as ViewStyle,
  SELECTEDCIRCLE_DOT_STYLE_FOR_SERVICE: {
    height: 10,
    width: 10,
    backgroundColor: color.palette.white,
    borderColor: color.palette.white,
    borderRadius: 5,
    borderWidth: 0.5,
    alignSelf: "center",
    justifyContent: 'center',
    alignItems: 'center',
    position: "absolute",
    top: 6,
    left: 6,
  } as ViewStyle,
  TXT_DATEOF_SERVICE: {
    color: color.palette.white,
    fontFamily: typography.primary,
  } as TextStyle,
  CONTAINEROF_DATE: {
    flexDirection: "row",
    width: screenWidth * 0.55,
    marginTop: screenWidth * 0.02,
  } as ViewStyle,
  CONTAINER_OTHER_DATE: {
    height: 50,
    marginTop: 20,
    flexDirection: "row",
    marginBottom: 10,
  } as ViewStyle,
  FROM_DATE_VIEW: {
    height: 50,
    width: "45%",
    marginRight: "5%",
    backgroundColor: color.palette.purpple,
  } as ViewStyle,
  TO_DATE_VIEW: {
    height: 50,
    marginLeft: "5%",
    width: "45%",
    backgroundColor: color.palette.purpple,
  } as ViewStyle,
  TXT_DATEOF_LABEL: {
    color: color.palette.white,
    fontFamily: typography.primary,
    fontSize: fontSizes.font14,
  } as TextStyle,
  FROM_DATE_VIEW_TOUCHABLE: {
    backgroundColor: color.palette.paleGreyTwo,
    paddingLeft: 10,
    height: 40,
    width: "100%",
    justifyContent: "center",
  } as ViewStyle,
  CONTAINER_CRAINE_DETAILS: {
    flexDirection: "row",
    marginHorizontal: 12,
    marginTop: 15,
    paddingVertical: 5,
    paddingHorizontal: 3,
  } as ViewStyle,
  UNSELECTEDCHECKBOX: {
    height: screenWidth * 0.053,
    width: screenWidth * 0.053,
    borderColor: color.palette.lightGreyBlue,
    borderWidth: 1,
  } as ViewStyle,
  RIGHTSIGNBUTTON_STYLE: {
    height: screenWidth * 0.04,
    width: screenWidth * 0.03,
    alignSelf: "center",
  } as ImageStyle,
  SELECTEDCHECKBOX: {
    height: screenWidth * 0.053,
    width: screenWidth * 0.053,
    borderColor: color.palette.pink,
    backgroundColor: color.palette.pink,
    borderWidth: 1,
    justifyContent: "center",
  } as ViewStyle,
  BTN_CHECKBOX_STYLE: {
    height: screenWidth * 0.053,
    width: screenWidth * 0.053,
  } as ViewStyle,
  TXT_CRAIN_GADI_NUMBER: {
    color: color.palette.white,
    fontSize: fontSizes.font15,
    fontFamily: typography.primary,
    marginLeft: 10,
  } as TextStyle,
  FLATLIST_STYLE_VEHICLE: {
    width: screenWidth * 0.87,
    alignSelf: "center",
    backgroundColor: color.palette.purpple,
  } as ViewStyle,
  TXT_CRANE_NUMBER: {
    fontSize: fontSizes.font14,
    fontFamily: typography.primary,
    fontWeight: 'bold',
    marginLeft: 15,
    marginTop: 15,
  } as TextStyle,
}
